// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using filmdiziarsivi.Data;

#nullable disable

namespace filmdiziarsivi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("filmdiziarsivi.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aksiyon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilim Kurgu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dram"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Komedi"
                        });
                });

            modelBuilder.Entity("filmdiziarsivi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 2,
                            Rating = 8.6999999999999993,
                            ReleaseYear = 1999,
                            Title = "Matrix",
                            TrailerUrl = "https://www.youtube.com/embed/vKQi3bBA1y8",
                            Views = 1500
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/embed/YoHD9XEInc0",
                            Views = 2000
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            Rating = 9.0,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/embed/EXeTwQWrcwY",
                            Views = 2500
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            Rating = 9.1999999999999993,
                            ReleaseYear = 1975,
                            Title = "Hababam Sınıfı",
                            TrailerUrl = "https://www.youtube.com/embed/rGZ4I6s3UeQ",
                            Views = 5000
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 3,
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1994,
                            Title = "Esaretin Bedeli",
                            TrailerUrl = "https://www.youtube.com/embed/6hB3S9bIaco",
                            Views = 3000
                        });
                });

            modelBuilder.Entity("filmdiziarsivi.Models.Movie", b =>
                {
                    b.HasOne("filmdiziarsivi.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("filmdiziarsivi.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
